name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gcc libsdl2-dev -y

      - name: Test with Make
        run: make test && ./test-gemu

      - name: Build with Make
        run: make release

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gemu
          path: ./gemu
          retention-days: 5
